export enum Permission {
  ACTIVO_OBTENER_UFVS_DEL_BCB_ACT = 'ACTIVO_OBTENER_UFVS_DEL_BCB_ACT',
  ACTIVO_OBTENER_UFVS_ACT = 'ACTIVO_OBTENER_UFVS_ACT',

  ACTIVO_VISUALIZAR_BITACORAS_ACT = 'ACTIVO_VISUALIZAR_BITACORAS_ACT',

  ACTIVO_CREAR_ACTIVO_ACT = 'ACTIVO_CREAR_ACTIVO_ACT',
  ACTIVO_OBTENER_ACTIVOS_ACT = 'ACTIVO_OBTENER_ACTIVOS_ACT',
  ACTIVO_EDITAR_ACTIVO_ACT= 'ACTIVO_EDITAR_ACTIVO_ACT',
  ACTIVO_ELIMINAR_ACTIVO_ACT = 'ACTIVO_ELIMINAR_ACTIVO_ACT',
  
  ACTIVO_OBTENER_USUARIOS = 'ACTIVO_OBTENER_USUARIOS', 
  
  ACTIVO_VER_PDF = 'ACTIVO_VER_PDF',

  ACTIVO_VER_QR = 'ACTIVO_VER_QR',

  ACTIVO_CREAR_GRUPO_CONTABLE_ACT = 'ACTIVO_CREAR_GRUPO_CONTABLE_ACT',
  ACTIVO_OBTENER_GRUPOS_CONTABLES_ACT = 'ACTIVO_OBTENER_GRUPOS_CONTABLES_ACT',
  ACTIVO_EDITAR_GRUPO_CONTABLE_ACT = 'ACTIVO_EDITAR_GRUPO_CONTABLE_ACT',
  ACTIVO_ELIMINAR_GRUPO_CONTABLE_ACT = 'ACTIVO_ELIMINAR_GRUPO_CONTABLE_ACT',

  ACTIVO_CREAR_ENTREGA_ACT = 'ACTIVO_CREAR_ENTREGA_ACT',
  ACTIVO_OBTENER_ENTREGA_ACT = 'ACTIVO_OBTENER_ENTREGA_ACT',
  ACTIVO_EDITAR_ENTREGA_ACT = 'ACTIVO_EDITAR_ENTREGA_ACT',
  ACTIVO_ELIMINAR_ENTREGA_ACT = 'ACTIVO_ELIMINAR_ENTREGA_ACT',

  ACTIVO_CREAR_DEVOLUCION_ACT = 'ACTIVO_CREAR_DEVOLUCION_ACT',
  ACTIVO_OBTENER_DEVOLUCION_ACT = 'ACTIVO_OBTENER_DEVOLUCION_ACT',
  ACTIVO_EDITAR_DEVOLUCION_ACT = 'ACTIVO_EDITAR_DEVOLUCION_ACT',
  ACTIVO_ELIMINAR_DEVOLUCION_ACT = 'ACTIVO_ELIMINAR_DEVOLUCION_ACT',

  ACTIVO_CREAR_PROVEEDOR_ACT= 'ACTIVO_CREAR_PROVEEDOR_ACT',
  ACTIVO_OBTENER_PROVEEDORES_ACT = 'ACTIVO_OBTENER_PROVEEDORES_ACT',
  ACTIVO_EDITAR_PROVEEDOR_ACT = 'ACTIVO_EDITAR_PROVEEDOR_ACT',
  ACTIVO_ELIMINAR_PROVEEDOR_ACT = 'ACTIVO_ELIMINAR_PROVEEDOR_ACT',
  ACTIVO_REESTABLECER_PROVEEDOR_ACT = 'ACTIVO_REESTABLECER_PROVEEDOR_ACT',

  ACTIVO_CREAR_ESTADO_ACT = 'ACTIVO_CREAR_ESTADO_ACT',
  ACTIVO_OBTENER_ESTADO_ACT = 'ACTIVO_OBTENER_ESTADO_ACT',
  ACTIVO_EDITAR_ESTADO_ACT = 'ACTIVO_EDITAR_ESTADO_ACT',
  ACTIVO_ELIMINAR_ESTADO_ACT = 'ACTIVO_ELIMINAR_ESTADO_ACT',
  ACTIVO_REESTABLECER_ESTADO_ACT = 'ACTIVO_REESTABLECER_ESTADO_ACT',

  ACTIVO_CREAR_PERMISO_ACT= 'ACTIVO_CREAR_PERMISO_ACT',
  ACTIVO_OBTENER_PERMISOS_ACT = 'ACTIVO_OBTENER_PERMISOS_ACT',
  ACTIVO_EDITAR_PERMISO_ACT = 'ACTIVO_EDITAR_PERMISO_ACT',
  ACTIVO_ELIMINAR_PERMISO_ACT = 'ACTIVO_ELIMINAR_PERMISO_ACT' ,
}
